server:
  port : 8081
url: "http://localhost:8081"
api:
  task:
    find: "/api/task/find"
folder: "folder"
spring:
  kafka:
    producer:
      topic: new_tasks
      id: producerServer
    group:
      id: Starship
    server: localhost:9092
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/postgres?currentSchema=test
    username: postgres
    password: 123456
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
logging:
  file:
    name: application.log
    path: logs